<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" href="./css/main.css">
</head>
<link href="./css/boardcss.css" rel="stylesheet" />
<body>
	<c:import url="topmenu.jsp" />
	<form action="index.do">
		<div id="listboard">
			<h2>공지사항</h2>
			<div id="listTop">
				<a id="writelink" href="">글쓰기</a>
			</div>

			<table>
				<tr>
					<th>제목</th>
					<th>닉네임</th>
					<th>날짜</th>
					<th>조회수</th>
				</tr>
				<tr>
					<td>공지공지공지공지공지공지공지공지</td>
					<td>주인장ㅇㅇㅇ</td>
					<td>오늘임</td>
					<td>38242</td>
				</tr>
				<tr>
					<td>ㅇㅁㅎㅁㄴㅇㄻㅇㄴㄹ</td>
					<td>주인장</td>
					<td>어제?</td>
					<td>3342</td>
				</tr>
				<tr>
					<td>공지공ㅁㄴㅇㄻㄷㄹㅈ공지</td>
					<td>주인장</td>
					<td>어제</td>
					<td>2822</td>
				</tr>
				<tr>
					<td>공지공지공지큨ㅌㅊㅌㅊㅍㄴㅇㄹ공지공지</td>
					<td>주인장</td>
					<td>모름</td>
					<td>242</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>
				<tr>
					<td>공지ㅈㄷ숃ㅄㅇㄴㄹㄴㅇㄹ공지</td>
					<td>주인장</td>
					<td>몰라</td>
					<td>32</td>
				</tr>

			</table>
			<div id="listBottom">
				<select>
					<option>선택</option>
					<option>전체</option>
					<option>제목</option>
					<option>작성자</option>
				</select> <input placeholder="검색하세요">
				<button>검색</button>
				<a id="writelink" href="">글쓰기</a>
			</div>

			<c:import url="bottonmenu.jsp" />
		</div>
	</form>
</body>
</html>